### ISSUE TITLE
Some releases are missing certain RPMs

### ISSUE THREAD

**Issue by der-eismann** [rabbitmq/erlang-rpm#92]
Hey everyone,

I just noticed that there are quite a few packages missing on the releases page. Some examples:
- [v23.0.3](https://github.com/rabbitmq/erlang-rpm/releases/tag/v23.0.3) & [v22.3.4.4](https://github.com/rabbitmq/erlang-rpm/releases/tag/v22.3.4.4) are missing EL6 & EL8 RPMs
- [v22.3.4.10](https://github.com/rabbitmq/erlang-rpm/releases/tag/v22.3.4.10) is missing the EL8 RPM

I downloaded them from packagecloud for now, so the RPMs are there, they just didn't get pushed to GitHub. It would be great if someone could fix the pipeline.

**Comment by michaelklishin** [comment]
I will produce and tag `23.0.4` now to see if this can be a timing issue in the pipeline. If so, it will have to wait until the pipeline that produces these packages is 100% automated (including detecting upstream tags). I updated the releases mentioned manually.

**Comment by michaelklishin** [comment]
The packages uploaded to GitHub as part of a release are taken from Bintray. If some of them are not available, looks like they won't get included:

``` yaml
  - name: tag-package-release-22
    serial: true
    plan:
      - in_parallel:
        - get: ci
          tags: [erlang-elixir]
        - get: centos-7-image
          tags: [erlang-elixir]
        - get: erlang-rpm-src-22
          tags: [erlang-elixir]
          passed:
            - build-erlang-rpm-22-el6
            - build-erlang-rpm-22-el7
            - build-erlang-rpm-22-el8
        - get: erlang-rpm-package-22-el8-on-bintray
          tags: [erlang-elixir]
          passed:
            - build-erlang-rpm-22-el8
        - get: erlang-rpm-package-22-el7-on-bintray
          tags: [erlang-elixir]
          passed:
            - build-erlang-rpm-22-el7
        - get: erlang-rpm-package-22-el6-on-bintray
          tags: [erlang-elixir]
          passed:
            - build-erlang-rpm-22-el6
      - task: format-tag
        tags: [erlang-elixir]
        image: centos-7-image
        file: ci/erlang-rpm/tasks/format-tag.yaml
        input_mapping:
          erlang-rpm-src: erlang-rpm-src-22
      - put: erlang-rpm-src-22
        tags: [erlang-elixir]
        params:
          repository: erlang-rpm-src-22
          tag: tag/tag
          only_tag: true
      - put: erlang-rpm-package-22-on-github
        tags: [erlang-elixir]
        params:
          name: github-release/name
          tag: tag/tag
          body: github-release/body
          globs:
          # A package version on Bintray contains all RPMs (for all CentOS versions)
           - 'erlang-rpm-package-22-el7-on-bintray/erlang/*/el/*/x86_64/erlang-*.rpm'
```

Concourse's `in_parallel` step [is supposed to fail of any of the steps do](https://concourse-ci.org/jobs.html#schema.step.in-parallel-step.in_parallel). So currently the question is why this does not happen.
